# tasks:
#   # init: cd server && npm install
#   - command: node server/index.js
#     openMode: split-right
# ports:
#   - port: 3000
#     onOpen: open-preview
image: node:18-alpine
tasks:
  - init: npm install
    command: npm start
