tasks:
  - name: Build and start services
    init: |
        npm install -g docker-compose
        docker-compose build
    command: docker-compose up -d
    ports:
      - 3000
      - 3478
      - 49152-65535
    openMode: split-right
