services:
  coturn:
    build:
      context: ./coturn
      dockerfile: Dockerfile
    container_name: coturn
    ports:
      - "${TURN_PORT}:${TURN_PORT}/tcp"
      - "${TURN_PORT}:${TURN_PORT}/udp"
    networks:
      - webrtc-network
    volumes:
      - ./coturn/turnserver.log:/var/log/turnserver.log
    restart: unless-stopped
    env_file:
      - .env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - webrtc-network
    depends_on:
      - coturn
    restart: unless-stopped
    env_file:
      - .env  # Thêm dòng này để server đọc file .env

networks:
  webrtc-network:
    driver: bridge