# Sử dụng Node.js base image
FROM node:18-alpine

# Tạo thư mục làm việc trong container
WORKDIR /app

# Sao chép file package.json và package-lock.json vào container
COPY server/package*.json ./

# Cài đặt các dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn ứng dụng vào container
COPY server .

# Khai báo cổng mà ứng dụng sẽ lắng nghe
EXPOSE 3000

# Lệnh chạy ứng dụng
CMD ["node", "index.js"]
